### ISSUE TITLE
Issue for the approximation of Monge map

### ISSUE THREAD

**Issue by harryjo97** [navid-naderi/WEGL#1]
If I understood the paper and the code correctly,
I believe this line of code for the approximation of Monge map : 

https://github.com/navid-naderi/WEGL/blob/73ac528dac71d03c09d0488dda3ad02c30f33905/WEGL/WEGL.py#L186

should be changed to 
`V[phase].append( (np.matmul((N * p).T, x) - template) * (N**(-0.5)) )`
from section 3.2 in the paper

please let me know if I am wrong

Thank you

**Comment by fulifeng** [comment]
I have the same question. Did you get any response from the authors through other connections?

**Comment by harryjo97** [comment]
Could you help let us know if this is correct? @navid-naderi

**Comment by navid-naderi** [comment]
I apologize for the delay, and thanks for the question! It is correct that adding ![formula](https://render.githubusercontent.com/render/math?math=1/\sqrt{N}) would make the formulation consistent with Section 3.2 of the paper. This term is used to simply convert the weighted-![formula](https://render.githubusercontent.com/render/math?math=\ell_2) distance between a given set of node embeddings and the reference distribution to regular ![formula](https://render.githubusercontent.com/render/math?math=\ell_2) distance. However, as we consider the reference distribution to be uniform, the difference is just a constant term that should not have a significant impact on the downstream performance, and since our evaluations in the paper were all based on the current formulation in the code, we prefer to keep it as is.

**Comment by harryjo97** [comment]
Thank you for the detailed reply.
